### ISSUE TITLE
Chart auto-update is not working

### ISSUE THREAD

**Issue by DanJamesH** [chartbrew/chartbrew#105]
Good day. First of all thanks to the creators of the app. It really is very cool.

On the surface level, my issue is quite simple. The charts I have created on my dashboard do not update even though I have specified the auto-update option to be every hour. 

As you can see in picture one the chart says it was updated a day ago.

![imageedit_3_5477801254](https://user-images.githubusercontent.com/47977629/152506720-4802d10b-2c64-4251-b89d-2a6b578acbf5.png)

Even though, in picture two, it can be seen that the auto-update interval is set to every hour.

![update](https://user-images.githubusercontent.com/47977629/152506840-78fb34de-2267-46f2-83e6-a192ff1e01c5.png)

To double check I went to the logs on AWS where my Chartbrew is hosted and no calls are even being made which makes me think that it is an issue on the Chartbrew side. I am not sure where this issue may lie. Some guidance for feedback would be most helpful. Has an one else experienced this before? Maybe I have set Chartbrew up with something missing?

Thank you for you time.

**Comment by razvanilin** [comment]
Hey @DanJamesH thanks for stopping by!

This was flagged to me on Discord a few days ago. There was an issue with the cron operation to update the charts automatically. This has been fixed in the latest version. Can you try an update your project and see if it works?

Feel free to re-open the issue if the problem persists
