### ISSUE TITLE
First signup problem

### ISSUE THREAD

**Issue by gokcenveysel** [chartbrew/chartbrew#106]
Hi,

I install chartbrew app as your guideline but when I try to signup for new user from client, I get error like below. How I can fix it?

Thanks

POST /user 400 27.802 ms - 2
(node:8577) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:455:11)
    at ServerResponse.header (/Users/xxxx/chartbrew/server/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/Users/xxxx/chartbrew/server/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/xxxx/chartbrew/server/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/xxxx/chartbrew/server/node_modules/express/lib/response.js:158:21)
    at /Users/veysel/chartbrew/server/api/UserRoute.js:84:32
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
(node:8577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8577) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

<img width="1038" alt="Screen Shot 2022-02-26 at 22 46 09" src="https://user-images.githubusercontent.com/11418591/155855434-b1f8e529-f787-4054-a577-8f8c6148f58a.png">

**Comment by gokcenveysel** [comment]
By the way, I can not see any .env file in chartbrew folder actually. I think I am missing somethings
<img width="332" alt="Screen Shot 2022-02-27 at 21 34 10" src="https://user-images.githubusercontent.com/11418591/155893095-4298577b-224a-4b6a-8a56-e6416c7687b1.png">

**Comment by razvanilin** [comment]
Thanks for coming back with more info! Not having the `.env` will definitely make the project not work. I'm assuming you ran the `create-chartbrew-app` on MacOS, right? I will look into it, but so far I couldn't replicate the issue on my Macbook. Can you let me know what version of NodeJS you are using?

You can try 2 things now to make it work:

1. Add a `.env` file to the root of your Chartbrew directory and add the required variables from https://docs.chartbrew.com/#environmental-variables (if you're not running the project in Production, make sure you append all variables with `_DEV` as mentioned at the top of the table there)

2. Start a new project by cloning the repository. Instead of using the `create-chartbrew-app` command, use the following:

```
git clone https://github.com/chartbrew/chartbrew.git
cd chartbrew && npm run setup
```

To learn more about how to set up the variables, check here: https://docs.chartbrew.com/#set-up-the-environmental-variables

**Comment by gokcenveysel** [comment]
Hi again @razvanilin,

I am using Node v12.5.0 and yes I am running on MacOS.

I will try your suggestions and give feedback again.

Thanks

**Comment by seyhunak** [comment]
Yes, I have the same issue with the Docker image, having "Server Error" after successfully pulling images and booting up.
2.nd option works for me too.

@razvanilin 
FYI @gokcenveysel

**Comment by razvanilin** [comment]
I will need to update the error message to be more explicit. `Server error` is a generic message for all kinds of errors. The most common issue is that the frontend app cannot reach the backend.

If you give the Docker image another try, double-check the env variables have the same format as in the examples (with `http://` or without).
