### ISSUE TITLE
🐛 [BLOCKING] Chartbrew front-end uses incorrect DNS name to access API service

### ISSUE THREAD

**Issue by pcgeek86** [chartbrew/chartbrew#142]
### Summary

The React web UI for Chartbrew attempts to access the API using `localhost` instead of the configured API server's DNS name.

This causes the sign-up process to fail, and I cannot proceed beyond the Chartbrew login screen

### Repro Steps

- **Device**: ODROID M1 (ARM64)
- **Operating System**: Ubuntu 22.04
- **Docker Engine**: Docker 20.10.12

I created a MySQL server in Docker, using this command:

```bash
docker run --detach --env MYSQL_ROOT_PASSWORD=12345 --net=host --restart=unless-stopped arm64v8/mysql
```

I spun up Chartbrew with Docker:

```
docker run --net=host \
  -e CB_SECRET=asdf \
  -e CB_API_HOST=0.0.0.0 \
  -e CB_API_PORT=4019 \
  -e CB_DB_HOST=localhost \
  -e CB_DB_NAME=chartbrew \
  -e CB_DB_USERNAME=root \
  -e CB_DB_PASSWORD=12345 \
  -e REACT_APP_CLIENT_HOST=http://myodroid.local:4018 \
  -e REACT_APP_API_HOST=http://myodroid.local:4019 \
  razvanilin/chartbrew:latest-arm64
```

- I accessed the web interface using `http://myodroid.local:4018`.
- The login page appears
- I click the "Sign Up" link
- I fill out the sign-up page
- When I submit the sign-up page, I get an error "_Failed to fetch_"
- When I examine the Google Chrome dev tools Network tab, I can see that Chartbrew front-end is accessing `localhost` instead of `myodroid.local`

<img width="279" alt="Screen Shot 2022-10-08 at 10 31 53 PM" src="https://user-images.githubusercontent.com/466713/194738177-5f02ee5c-65ef-470c-9806-38d0207aa221.png">

The error coming back is "**Connection Refused**" because API Server is not running on my local workstation, `localhost`. It's running on the remote device.

<img width="1597" alt="Screen Shot 2022-10-08 at 10 41 13 PM" src="https://user-images.githubusercontent.com/466713/194738434-97979d35-bcc2-4369-8d68-ebf7e6ca6fb9.png">

**Comment by razvanilin** [comment]
Hey @pcgeek86 issue is that the front-end application needs to be rebuilt. This step is necessary when changing the environmental variables.

It wasn't like this in previous versions, but the build command has been moved in the Dockerfile to avoid downtimes when restarting the container (because otherwise the build command would run at every restart).

To rebuild the frontend, you can run the following:

> ```shell
> # replace 'your_container_name' with the name of your docker container where Chartbrew is running
> 
> docker exec -it -w /code/client your_container_name npm run build
> ```

**Comment by razvanilin** [comment]
Closing this as with the newest version of Chartbrew, the UI gets rebuilt automatically in the background. When new changes are pulled or if the container is restarted, the build process runs in the background and will be available as soon as it's finished. The old UI will still run in order to minimised downtime
