### ISSUE TITLE
Mongo Connection

### ISSUE THREAD

**Issue by anmolmalik97** [chartbrew/chartbrew#149]
Hi Team. I'm new to chartbrew. I've cloned this repository and have managed to get it up and running. I've my application DB hosted on Mongo and on chartbrew website it says I can connect chartbrew to mongo but I really couldn't find any way to connect it to a mongo database.

Thanks in advance for the help.

**Comment by razvanilin** [comment]
Hey! I will need a few more details to be able to see where the issue is. Can you provide more info about the following (or anything else you think it's related):

* Where are you hosting your DB in relation to Chartbrew
* How did you try to connect to the DB?
* Did you get any errors when you tried to connect? If yes, please share error logs
