### ISSUE TITLE
Unable to run client and server with one command

### ISSUE THREAD

**Issue by saloni137** [chartbrew/chartbrew#176]
There should be a single command in package.json of the root folder, which can run the client and server with a single npm command.

**Comment by saloni137** [comment]
I can work on this issue and create a PR. please assign it to me.

**Comment by razvanilin** [comment]
Hey @saloni137 both processes for running the apps in `development` are daemons that should be managed separately, hence I don't think it's a good idea to try and run it from the same command. For example, having to change to automatically restart instances when code has changed will not work

In `production`, however, there's no need for this as only the server is running as a daemon.

Can you let me know more about your use case to warrant the need for a single-command run?

**Comment by saloni137** [comment]
Going to the client and server, separately and doing npm i can be a tedious job. Instead, we can make a package.json containing all the packages and do npm i in the root folder. and then starting/re-starting the client and server with a single command would be seamless for developers trying to run the project. 
It's just my suggestion.

**Comment by razvanilin** [comment]
If you thought the process was tedious when setting up and running the project, I would be happy to look at some code to see how this can be improved. The project is always open to PRs and I'm happy to check all of them

Here's a quick explanation of the current Chartbrew architecture to get a better understanding of why things are like they are right now:

Chartbrew is composed of two applications `client` and `server` which live separately from each other (e.g. you can have `server` running on machine1 and `client` on machine2). Bringing all dependencies in one package.json is definitely a no-go for now as that will break and complicate a lot of things.

That said, the project has a `package.json` in the root folder already that includes a `setup` script that installs all the dependencies for both projects. There is no script for running both apps because in `development` you generally want to manage processes separately. If there is one command to run both, you lose control over the management side of things.

**Comment by saloni137** [comment]
Also, I did check the root folder's package.json. There is a script to run the client and server from the root itself. that should be mentioned in the readme instead of `cd server && npm start`

**Comment by razvanilin** [comment]
The setup part is covered in the readme here: https://github.com/chartbrew/chartbrew#clone-and-setup

In regards to the start commands, those are still two commands since the `client` and `server` need to be run separately. The readme guides the devs to run it separately from their respective folders as that covers all use cases, even when the client and server are running on different machines.

For example, the commands from the root `package.json` cannot be run when the client project runs on somewhere like Vercel or Render

**Comment by saloni137** [comment]
okay understood.
