### ISSUE TITLE
#Error when running :  npm run db:migrate

### ISSUE THREAD

**Issue by mlodimanahan** [chartbrew/chartbrew#185]
Hi , im having a trouble when I open the new project I received from other developer. I tried to execute npm run db:migrate but the result is

npm ERR! Missing script: "db:migrate"
npm ERR!   npm run

**Comment by razvanilin** [comment]
Hey @mlodimanahan we removed that script a long time ago and the database migration is done automatically when running the back-end application

**Comment by razvanilin** [comment]
Actually, I just noticed that the script is still available, but you need to run the command in the `/server` folder. Although, as mentioned above, you don't have to manually run this command anymore as the migrations are done automatically when running the `/server` project

**Comment by mlodimanahan** [comment]
hello @razvanilin , tried running same command inside server folder. but I got this result.

dockerize-usermanager\server\server> npm run db:migrate

> user manager api@1.0.0 db:migrate
> sequelize db:migrate

The system cannot find the path specified.

**Comment by razvanilin** [comment]
Can you let me know what's the reason behind using that command? It's not needed to run that command anymore

**Comment by mlodimanahan** [comment]
Hi @razvanilin , I received a package from my colleague. he mentioned that I need to execute these 2 commands so it will be connected in postgres(using docker-compose.

npm install -g sequelize-cli pg and npm run db:migrate

**Comment by razvanilin** [comment]
The migrations have been automated a long time ago, so don't worry about running that command anymore 👌 What version are your currently on?

**Comment by mlodimanahan** [comment]
The problem is when I run the docker compose and tried to login its not going to the next page seems like it is not connected in DB/Postgres

**Comment by razvanilin** [comment]
My guess is that the UI does not connect to the backend rather than the DB connection being the issue. The most common problem stands with settings the wrong env variables.

Check if the following is set: `CB_API_HOST=0.0.0.0`
The `REACT_*` variables need to be set with the right protocol `http` or `https` depending on your use-case
Also `CB_DB_DIALECT=postgres`

You can double-check the format and requirements of the variables over here: https://docs.chartbrew.com/#environmental-variables

**Comment by mlodimanahan** [comment]
is that the env file?

**Comment by razvanilin** [comment]
Yes, you can use and `.env` file that is in the same folder as your docker-compose file.

Example vars with Docker: https://github.com/chartbrew/chartbrew#quickstart
Check here for all required vars and their description: https://docs.chartbrew.com/#environmental-variables

**Comment by mlodimanahan** [comment]
Hi, in my case im using docker compose and im running/connecting in postgres using that tool. Tried the one in the link you provided but the result is cannot find tha path specified.

**Comment by razvanilin** [comment]
you can still use the `.env` file if you use docker compose.

The `cannot find path specified` is from the migrate option that **you don't have to run**. It's also because you don't run in the right folder.

Not sure exactly what instructions the other developer left for you, but I would start from scratch and follow the instructions in this repository on how to start with Docker: https://docs.chartbrew.com/deployment/#run-the-application-with-docker 

I'm closing this as this is not an issue with the Project. If you want to get more help over this, please feel free to join our Discord: https://discord.gg/KwGEbFk
