### ISSUE TITLE
Ensuring Coexistence of Multiple Sessions

### ISSUE THREAD

**Issue by alb3rtod** [chartbrew/chartbrew#242]
Hi! We are facing an issue where, when someone is building datasets or charts and the CPU reaches 99% or a little more, it seems like the usage is throttled at that level (100%):

![image](https://github.com/user-attachments/assets/4938e81d-2358-4ac8-a358-42dc2ca9fa6b)

And if someone else (another user of Chartbrew) tries to view the dashboard or perform other actions, the UI only shows a loading circle and does not load until the dataset or chart building is finished by the other user:

![image](https://github.com/user-attachments/assets/9cdf555a-a069-4c96-aba0-c24bfbb44d23)

Is there any way to allocate more host resources to Chartbrew to allow multiple sessions to coexist?

**Comment by razvanilin** [comment]
You can use something like [pm2](https://pm2.keymetrics.io/docs/usage/cluster-mode/) to run the application in a cluster. I replied to your discussion about it and will essentially be the answer to the issue here. [Have a look at the answer here](https://github.com/chartbrew/chartbrew/discussions/241#discussioncomment-10270689)
